<?php
// $Id$

/**
 * @file
 * Automatically saves a node after a period of time.
 */

/**
 * Implementation of hook_help().
 */
function autosave_help($section) {
  switch ($section) {
    case 'admin/help#autosave':
      $output = '<p>'. t('The autosave module automatically save a node during adding or editing after a span of time.') .'</p>';
      return $output;
  }
}

/**
 * Implementation of hook_menu().
 */
function autosave_menu($may_cache) {
  global $user;
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/autosave', 
      'title' => t('Autosave save'),
      'callback' => 'autosave_save', 
      'access' => user_access('administer nodes'),
      'type' => MENU_CALLBACK,
    );
    
    $items[] = array(
      'path' => 'admin/content/types/autosave',
      'title' => t('Autosave'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('autosave_admin_settings'),
      'access' => user_access('administer nodes'),
      'type' => MENU_LOCAL_TASK,
    );
  }

  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function autosave_form_alter($form_id, &$form) {
  $content_types = array_filter(variable_get('autosave_content_types', array()));
  if (isset($form['type']) && in_array($form['type']['#value'], $content_types) && $form['type']['#value'] .'_node_form' == $form_id) {
    drupal_add_js(drupal_get_path('module', 'autosave') . '/autosave.js');
    drupal_add_js(drupal_get_path('module', 'autosave') . '/form.js');
    
    $url = url('admin/autosave');
    $period = variable_get('autosave_period', 10000);
    
    drupal_add_js('$(function() { setTimeout("autosave(' . "'" . $url . "', " . $period . ')", ' . $period . '); });', 'inline');
    
    if (arg(1) == 'add' && !$form['#post']) {
      unset($_SESSION['nid']);
    }
    
    $form['nid'] = array(
      '#type' => 'hidden',
      '#value' => $form['#node']->nid,
    );
    $form['vid'] = array(
      '#type' => 'hidden',
      '#value' => $form['#node']->vid,
    );
    $form['type'] = array(
      '#type' => 'hidden',
      '#value' => $form['#node']->type,
    );
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function autosave_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  switch ($op) {
    case 'submit':
      if ($node->op == 'Submit' && $_SESSION['nid']) {
        $node->nid = $_SESSION['nid'];
        $node->vid = $_SESSION['vid'];
        $node->log = '';
        $node->revision = 1;
                
        unset($_SESSION['nid']);
        unset($_SESSION['vid']);
        break;
      }
  }
}

/**
 * Menu callback; return the autosave module settings form.
 */
function autosave_admin_settings() {
  $types = node_get_types();
  
  foreach ($types as $type) {
    $options[$type->type] = $type->name;
  }
  
  $form['autosave_content_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Enable autosave for the following content types'),
    '#options' => $options,
    '#default_value' => variable_get('autosave_content_types', 0),
  );
  
  $form['autosave_period'] = array(
    '#type' => 'textfield',
    '#title' => t('Autosave after this amount milliseconds has passed'),
    '#default_value' => variable_get('autosave_period', 10000),
  );
  
  return system_settings_form($form);
}

/**
 * Menu callback; autosaves the node.
 */
function autosave_save() {
  $node = array();
  
  $node['title'] = $_REQUEST['title'];
  $node['body'] = $_REQUEST['body'];
  $node['type'] = $_REQUEST['type'];
  $node['format'] = $_REQUEST['format'];
  $node['comment'] = $_REQUEST['comment'];
  $node['taxonomy'] = $_REQUEST['taxonomy'];
  $node['name'] = $_REQUEST['name'];
  $node['date'] = $_REQUEST['date'];
  $node['status'] = 0;
  $node['promote'] = 0;
  $node['sticky'] = 0;
  $node['revision'] = $_REQUEST['revision'];
  
  
  if ($_REQUEST['nid']) {
    // Autosaving while editing an existing node
    $_SESSION['nid'] = $_REQUEST['nid'];
    $_SESSION['vid'] = $_REQUEST['vid'];
    $node['nid'] = $_SESSION['nid'];
    $node['vid'] = $_SESSION['vid'];
    $node['revision'] = 1;
  }
  else {
    if ($_SESSION['nid']) {
      // Autosaving a node that was autosaved previously
      $node['nid'] = $_SESSION['nid'];
      $node['vid'] = $_SESSION['vid'];
    }
    else {
      // Autosaving a new node, session variable are set for next autosave
      $_SESSION['nid'] = db_result(db_query("SELECT id FROM {sequences} WHERE name = '%s'", 'node_nid')) + 1;
      $_SESSION['vid'] = db_result(db_query("SELECT id FROM {sequences} WHERE name = '%s'", 'node_revisions_vid')) + 1;
    }
  }
  
  $log = 'Autosaved at ' . date('g:i:s a');
  $node['log'] = $log;
  
  $node = (object)$node;
  $node = node_submit($node);
  node_save($node);
  db_query("UPDATE {node} SET changed = %d WHERE nid = %d", 0, $node->nid);
  
  echo '<em>' . $log . '</em>';
}
